### ISSUE TITLE
C++ reference problem using mat_to_numpy

### ISSUE THREAD

**Issue by AnthonyBeeblebrox** [andrewcron/cy_armadillo#3]
Hello and big thanks for cy_armadillo,
Here is a little problem I encountered when using mat_to_numpy: 

"pytest.pyx": 
------------------------------------------------------------------------------------
	include "cyarma/cyarma.pyx"
	import numpy as np
	cimport numpy as np

	cdef extern from "testMatrix.h":
	mat test(mat & M)

	def py_test(M):
	return mat_to_numpy(test(numpy_to_mat_d(M)),None)
------------------------------------------------------------------------------------

"testMatrix.h":
------------------------------------------------------------------------------------
	#include "armadillo"
	arma::mat test(arma::mat const& M){
		return M+M;
	}

	The compilation with "python setup.py build_ext --inplace" raise : 
------------------------------------------------------------------------------------
	pytest.cpp: In function ‘PyObject* __pyx_pf_7pytest_32py_test(PyObject*, PyObject*)’:
	pytest.cpp:5166:153: erreur: invalid initialization of non-const reference of type ‘arma::mat& {aka arma::Mat<double>&}’ from an rvalue of type ‘arma::mat {aka arma::Mat<double>}’
	pytest.cpp:2330:23: erreur: in passing argument 1 of ‘PyArrayObject* __pyx_f_7pytest_mat_to_numpy(arma::mat&, PyArrayObject*)’
	error: command 'gcc' failed with exit status 1

The problem seemed solved by supressing the "&" in cyarma.pyx in mat_to_numpy : 
------------------------------------------------------------------------------------
	@cython.boundscheck(False)
	cdef np.ndarray[np.double_t, ndim=2] mat_to_numpy(mat ----> & <---- X, np.ndarray[np.double_t, ndim=2] D):
	    cdef double * Xptr = X.memptr()
	    
	    if D is None:
		D = np.empty((X.n_rows, X.n_cols), dtype=np.double, order="F")
	    cdef double * Dptr = <double*> D.data
	    for i in range(X.n_rows*X.n_cols):
		Dptr[i] = Xptr[i]
	    return D
------------------------------------------------------------------------------------

Hope that'll help you, good luck.

**Comment by andrewcron** [comment]
I think the problem is in `mat_to_numpy(test(numpy_to_mat_d(M)),None)` ... `test` returns a `mat` in a temporary rvalue which can only be referenced as a constant. I think a better fix is to change `mat_to_numpy` to 

```
@cython.boundscheck(False)                                                                                                                                                                                               
cdef np.ndarray[np.double_t, ndim=2] mat_to_numpy(const mat & X, np.ndarray[np.double_t, ndim=2] D):                                                                                                                     
    cdef const double * Xptr = X.memptr()                                                                                                                                                                                
                                                                                                                                                                                                                         
    if D is None:                                                                                                                                                                                                        
        D = np.empty((X.n_rows, X.n_cols), dtype=np.double, order="F")                                                                                                                                                   
    cdef double * Dptr = <double*> D.data                                                                                                                                                                                
    for i in range(X.n_rows*X.n_cols):                                                                                                                                                                                   
        Dptr[i] = Xptr[i]                                                                                                                                                                                                
    return D      
```
This will preserve the pass-by-reference efficiency of the current approach and should remedy the function chaining.

Does this approach fix your case? (I will try to replicate later. I don't have time now.)
